name: actrec-directory
services:
- name: web
  source_dir: /
  github:
    repo: your-username/telephone-directory
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: your-supabase-url
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: your-supabase-key
  http_port: 3000